# Form implementation generated from reading ui file 'votingGui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VotingSheet(object):
    def setupUi(self, VotingSheet):
        VotingSheet.setObjectName("VotingSheet")
        VotingSheet.resize(200, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VotingSheet.sizePolicy().hasHeightForWidth())
        VotingSheet.setSizePolicy(sizePolicy)
        VotingSheet.setMinimumSize(QtCore.QSize(200, 300))
        VotingSheet.setMaximumSize(QtCore.QSize(200, 300))
        self.centralwidget = QtWidgets.QWidget(parent=VotingSheet)
        self.centralwidget.setObjectName("centralwidget")
        self.johnRadioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.johnRadioButton.setGeometry(QtCore.QRect(40, 30, 161, 21))
        self.johnRadioButton.setObjectName("johnRadioButton")
        self.janeRadioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.janeRadioButton.setGeometry(QtCore.QRect(40, 60, 161, 21))
        self.janeRadioButton.setObjectName("janeRadioButton")
        self.votingLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.votingLabel.setGeometry(QtCore.QRect(10, 0, 181, 20))
        self.votingLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.votingLabel.setObjectName("votingLabel")
        self.otherRadioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.otherRadioButton.setGeometry(QtCore.QRect(40, 90, 161, 17))
        self.otherRadioButton.setObjectName("otherRadioButton")
        self.otherLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.otherLineEdit.setGeometry(QtCore.QRect(40, 110, 113, 20))
        self.otherLineEdit.setObjectName("otherLineEdit")
        self.idLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.idLabel.setGeometry(QtCore.QRect(0, 140, 201, 21))
        self.idLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.idLabel.setObjectName("idLabel")
        self.idLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.idLineEdit.setGeometry(QtCore.QRect(40, 170, 113, 21))
        self.idLineEdit.setObjectName("idLineEdit")
        self.submitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(60, 210, 75, 23))
        self.submitButton.setObjectName("submitButton")
        VotingSheet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VotingSheet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 200, 21))
        self.menubar.setObjectName("menubar")
        VotingSheet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VotingSheet)
        self.statusbar.setObjectName("statusbar")
        VotingSheet.setStatusBar(self.statusbar)

        self.retranslateUi(VotingSheet)
        QtCore.QMetaObject.connectSlotsByName(VotingSheet)

    def retranslateUi(self, VotingSheet):
        _translate = QtCore.QCoreApplication.translate
        VotingSheet.setWindowTitle(_translate("VotingSheet", "Voting Sheet"))
        self.johnRadioButton.setText(_translate("VotingSheet", "John Doe"))
        self.janeRadioButton.setText(_translate("VotingSheet", "Jane Doe"))
        self.votingLabel.setText(_translate("VotingSheet", "Voting Sheet"))
        self.otherRadioButton.setText(_translate("VotingSheet", "Other Candidate"))
        self.idLabel.setText(_translate("VotingSheet", "Please enter an ID number (5 digits)"))
        self.submitButton.setText(_translate("VotingSheet", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VotingSheet = QtWidgets.QMainWindow()
    ui = Ui_VotingSheet()
    ui.setupUi(VotingSheet)
    VotingSheet.show()
    sys.exit(app.exec())
