# Form implementation generated from reading ui file 'votingGui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VotingSheet(object):
    def setupUi(self, VotingSheet):
        VotingSheet.setObjectName("VotingSheet")
        VotingSheet.resize(200, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VotingSheet.sizePolicy().hasHeightForWidth())
        VotingSheet.setSizePolicy(sizePolicy)
        VotingSheet.setMinimumSize(QtCore.QSize(200, 300))
        VotingSheet.setMaximumSize(QtCore.QSize(200, 300))
        self.centralwidget = QtWidgets.QWidget(parent=VotingSheet)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(40, 30, 161, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 50, 161, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 181, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 70, 161, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 90, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 130, 201, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 160, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        VotingSheet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VotingSheet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 200, 21))
        self.menubar.setObjectName("menubar")
        VotingSheet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VotingSheet)
        self.statusbar.setObjectName("statusbar")
        VotingSheet.setStatusBar(self.statusbar)

        self.retranslateUi(VotingSheet)
        QtCore.QMetaObject.connectSlotsByName(VotingSheet)

    def retranslateUi(self, VotingSheet):
        _translate = QtCore.QCoreApplication.translate
        VotingSheet.setWindowTitle(_translate("VotingSheet", "Voting Sheet"))
        self.radioButton.setText(_translate("VotingSheet", "John Doe"))
        self.radioButton_2.setText(_translate("VotingSheet", "Jane Doe"))
        self.label.setText(_translate("VotingSheet", "Voting Sheet"))
        self.radioButton_3.setText(_translate("VotingSheet", "Other Canidate"))
        self.label_2.setText(_translate("VotingSheet", "Please enter an ID number (5 digits)"))
        self.pushButton.setText(_translate("VotingSheet", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VotingSheet = QtWidgets.QMainWindow()
    ui = Ui_VotingSheet()
    ui.setupUi(VotingSheet)
    VotingSheet.show()
    sys.exit(app.exec())
